In [16]:
import tensorflow as tf
import numpy as np
from pprint import pprint

# If using seed to replicate results.
# np.random.seed(22)

dt = 0.05  # time between each time step in the simulation.
num_inputs = 3  # Number of Values output by the simulation
num_outputs = 1 # OpenAI env takes a single controller input, thus the controller network must output only one.
num_nodes = num_inputs+1  # Number of nodes in the network (must be >=nump_inputs)
num_epochs = 10
initial_state = np.random.randn(num_nodes,1) #tf.zeros([num_nodes,1],dtype=tf.float32)



# class D_RNN():
#     def __init__(self):
#         self.create_network()
        
def create_network(set_weights=None,set_bias=None):
    """

    Args:
        set_weights - the weights for the RNN dimensions of (num_nodes+num_outputs,num_nodes)
        
    Returns:
        input - placeholder in the network to input values
        output - output 
        update_state -
    """
    # _______________________________________
    #               Setting shit
    # _______________________________________
    # Randomly set the wieghts when initializing else set them to whats been given.
    if (not set_weights): set_weights = np.random.randn(num_nodes+num_outputs,num_nodes)*0.1

    print('Setting weights automatically')
    # if (not set_bias):
    print('Setting bias automatically')
    set_bias = np.zeros([num_nodes+num_outputs,1],dtype=np.float32)


    # _______________________________________
    #               Variables
    # _______________________________________

    # Each input variable feeds into one node
    _input = tf.placeholder(tf.float32,[num_inputs,1])  # Dim 1 = 1 as this is a dynamic task that only takes one input at a time
    _input_buffer = tf.zeros([num_nodes-num_inputs,1],dtype=tf.float32)  # used so add the input to the state in one step.

    # Concatenate the inputs
    I = tf.concat([_input,_input_buffer],0)
    print(type(set_weights))
    # Create the weights for the RNN
    W = tf.Variable(set_weights, dtype=tf.float32) # could be a constant...
    b = tf.Variable(set_bias, dtype=tf.float32) # could also be a constant...

    state = tf.Variable(initial_state,dtype=tf.float32)

    # _______________________________________
    #               Operations
    # _______________________________________
    Wx = tf.matmul(W,state)
    Wx_b = Wx+b
    recurrence, output = tf.split(Wx_b,[num_nodes,num_outputs],0)

    output = tf.tanh(output) * 2

    next_state = state + dt * (-state+tf.tanh(recurrence + I))

    update_state = state.assign(next_state)
    
    return _input, output, W, state



_input,output, weights, update_state = create_network()

_input2,output2, weights2, update_state2 = create_network()

print("Output1")
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)

#     print(I.eval(session=sess))


    out_list = list()
#     _in = np.random.randn(num_inputs,1)
    _in = np.zeros([num_inputs,1],dtype=np.float32)
    for epoch in range(num_epochs):
        _, out = sess.run([update_state, output],feed_dict={_input:_in})
        out_list.append(out)
pprint(out_list)

print()
print("Output2")
with tf.Session() as sess2:
    init2 = tf.global_variables_initializer()
    sess2.run(init2)

#     print(I.eval(session=sess))


    out_list2 = list()
#     _in = np.random.randn(num_inputs,1)
    _in2 = np.zeros([num_inputs,1],dtype=np.float32)
    for epoch in range(num_epochs):
        _, out2 = sess2.run([update_state2, output2],feed_dict={_input2:_in2})
        out_list2.append(out2)
        
pprint(out_list2)

print()
print("Output1.2")
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)

#     print(I.eval(session=sess))


    out_list = list()
#     _in = np.random.randn(num_inputs,1)
    _in = np.zeros([num_inputs,1],dtype=np.float32)
    for epoch in range(num_epochs):
        _, out = sess.run([update_state, output],feed_dict={_input:_in})
        out_list.append(out)
        

pprint(out_list)
print('hello')
# pprint(out_list2)

print("Output1.2")
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)

#     print(I.eval(session=sess))


    out_list = list()
#     _in = np.random.randn(num_inputs,1)
    _in = np.zeros([num_inputs,1],dtype=np.float32)
    for epoch in range(num_epochs):
        _, out = sess.run([update_state, output],feed_dict={_input:_in})
        out_list.append(out)
        

pprint(type(out))
print('hello')
# pprint(out_list2)

Setting weights automatically
Setting bias automatically
<class 'numpy.ndarray'>
Setting weights automatically
Setting bias automatically
<class 'numpy.ndarray'>
Output1
[array([[ 0.04559202]], dtype=float32),
 array([[ 0.04559202]], dtype=float32),
 array([[ 0.04559202]], dtype=float32),
 array([[ 0.04559202]], dtype=float32),
 array([[ 0.04559202]], dtype=float32),
 array([[ 0.04559202]], dtype=float32),
 array([[ 0.04559202]], dtype=float32),
 array([[ 0.04559202]], dtype=float32),
 array([[ 0.04559202]], dtype=float32),
 array([[ 0.04559202]], dtype=float32)]

Output2
[array([[-0.13152753]], dtype=float32),
 array([[-0.13152753]], dtype=float32),
 array([[-0.13152753]], dtype=float32),
 array([[-0.13152753]], dtype=float32),
 array([[-0.13152753]], dtype=float32),
 array([[-0.13152753]], dtype=float32),
 array([[-0.13152753]], dtype=float32),
 array([[-0.13152753]], dtype=float32),
 array([[-0.13152753]], dtype=float32),
 array([[-0.13152753]], dtype=float32)]

Output1.2
[array([[ 

## Update wieghts

In [35]:
print(weights.shape)
print(np.random.rand(5,4).shape)
# with tf.Session() as sess:
#     weights.eval()

with tf.Session() as sess:
    
    _ = weights.assign(np.random.rand(5,4))
    sess.run(_)
    x = weights.eval()
    print((weights.eval()))
#     print(I.eval(session=sess))


#     out_list = list()
# #     _in = np.random.randn(num_inputs,1)
#     _in = np.zeros([num_inputs,1],dtype=np.float32)
#     for epoch in range(num_epochs):
#         _, out = sess.run([update_state, output],feed_dict={_input:_in})
#         out_list.append(out)
        

# pprint(out_list)
print('hello')
# pprint(out_list2)

(5, 4)
(5, 4)
[[ 0.6482929   0.73822057  0.32637706  0.8568725 ]
 [ 0.22045712  0.70231336  0.80156964  0.62236881]
 [ 0.25379252  0.11639043  0.62406945  0.30842981]
 [ 0.5354023   0.03419872  0.97649145  0.69419634]
 [ 0.6882661   0.2703771   0.43076929  0.22229286]]
hello


In [41]:
y = x.flatten()
print(y)
z = y.reshape(5,4)
print(z)

[ 0.6482929   0.73822057  0.32637706  0.8568725   0.22045712  0.70231336
  0.80156964  0.62236881  0.25379252  0.11639043  0.62406945  0.30842981
  0.5354023   0.03419872  0.97649145  0.69419634  0.6882661   0.2703771
  0.43076929  0.22229286]
[[ 0.6482929   0.73822057  0.32637706  0.8568725 ]
 [ 0.22045712  0.70231336  0.80156964  0.62236881]
 [ 0.25379252  0.11639043  0.62406945  0.30842981]
 [ 0.5354023   0.03419872  0.97649145  0.69419634]
 [ 0.6882661   0.2703771   0.43076929  0.22229286]]


In [3]:
W = tf.Variable(np.array([0,0]), dtype=tf.float32) # could be a constant...

In [95]:
x = (np.ndarray(20,dtype=np.float32,buffer=np.random.randn(30,dtype=np.float64)))

TypeError: randn() got an unexpected keyword argument 'dtype'

In [93]:
for i in range(len(x)):
    print(int(x[i]))
print(x)

144809743703127563320034328576
-1
0
-1
-7740
-1
0
-1
15154207694765582530415231264266125312
-1
0
-1
2004269268992
-1
-159798368665600
-1
0
-1
0
-1
[  1.44809744e+29  -1.53880596e+00  -1.77189452e-03  -1.80627823e+00
  -7.74072754e+03  -1.82374251e+00  -1.05827713e-27  -1.78213370e+00
   1.51542077e+37  -1.65595436e+00  -9.76384407e-16  -1.94887066e+00
   2.00426927e+12  -1.88745439e+00  -1.59798369e+14  -1.82660890e+00
   8.64459241e-28  -1.88203919e+00   5.80202697e-38  -1.75078058e+00]


In [122]:
print(np.ndarray(shape=(20,),dtype=np.float64,buffer=np.random.rand(20),order='C'))

[ 0.90465512  0.26513949  0.10382357  0.22045395  0.66880977  0.69013287
  0.26185601  0.14889424  0.68326228  0.93419833  0.63279823  0.41949724
  0.03218025  0.40777749  0.01496023  0.50798798  0.83998934  0.236279
  0.8988143   0.7319778 ]


In [129]:
x = np.ndarray(shape=(20),buffer=np.random.rand(20)).astype(np.float32)
print(x)
y = x.astype(np.float32)
print(type(y[0]))

[ 0.97750711  0.06729285  0.216847    0.97305167  0.96610582  0.88966554
  0.68340278  0.0358297   0.82549763  0.10041883  0.28043225  0.87453747
  0.31804729  0.01632436  0.73075151  0.8514083   0.15043195  0.05581134
  0.04836659  0.47963995]
<class 'numpy.float32'>


In [117]:
y = np.ndarray(shape=20,buffer=x,dtype=np.float32)

In [132]:
x = np.random.rand(20).astype(np.float32)
print(type(x))
y = x.astype(np.float32)
print(type(y[0]))

<class 'numpy.ndarray'>
<class 'numpy.float32'>
