## A session is a container class for the computational graph.

In [ ]:
import collections
sesh = tf.Session()
b = tf.constant([10,20])
a = tf.constant([[1],[2]])
c = tf.matmul(a,b)
v = sesh.run(c)
print(v)

In [54]:
import tensorflow as tf
x = tf.Variable(0)
y = tf.assign(x, 1)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print (sess.run(y))
    print (sess.run(x))

1
1


In [65]:
from pprint import pprint
MyData = collections.namedtuple('MyData',['a','b'])
v = sesh.run({'k1':MyData(a,b),'k2':[b,a]})
pprint.pprint(v)

from pprint import pprint
import numpy as np
import tensorflow as tf

nodes = 2  # Number of nodes in the RNN

S1 = tf.placeholder(tf.float32,shape=(2,1))  # The (sensory) input at every timestep

W = tf.Variable([[1,1],[1,1]],dtype=tf.float32)  # The weights to be set by a GA
b = tf.Variable(np.zeros((nodes,1)),dtype=tf.float32)  # bias parameter, allowing node to learn offset
prev_state = tf.Variable(np.zeros((nodes,1)),dtype=tf.float32)

with tf.name_scope('Wx_b_sensory_in') as scope:
    mul = tf.matmul(W,S1)
    add = tf.add(mul, b)
    add = tf.add(add,prev_state)
    y1 = tf.nn.tanh(add)
    # Ends with shape 2,1

# Weights and biases to be for hidden/next_time state
W2 = tf.Variable([[1.1,-1],[-1,1.1]],dtype=tf.float32)
b2 = tf.Variable(np.zeros((nodes,1)),dtype=tf.float32)

with tf.name_scope('Wy_b') as scope:
    yh = tf.nn.tanh(tf.matmul(W2,y1)+b2) # Next t_step values
    

dt = 0.1

with tf.Session() as sess:
    one = sess.run(tf.global_variables_initializer())
    three = sess.run(yh,feed_dict={S1:[[1],[1]]})
    
    motor_controls = []
    motor_controls.append(three)
    
    for epoch in range(100):
        print(prev_state)
        sess.run(y1,feed_dict={S1:np.array([[1],[1]],dtype=np.float32)})
        sess.run(yh)
        #_ = tf.assign(prev_state,y1)
        pprint(y1)
        if epoch%10==0: print('epoch: '+str(epoch+1))

    
# W2 = tf.Variable([[1,1],[1,1]],dtype=tf.float32)  # The weights to be set by a GA
# b2 = tf.Variable(np.zeros((1,nodes)))  # bias parameter, allowing node to learn offset


# def rnn_cell(, W, b, W2, b2, nodes=2):
#     """

#     Args:
#         W - The weights set by the GA
#         b -
#         W2 - 
#         B2 -

#     Kwargs:
#         nodes - The number of nodes in the RNN
#     """

    
#     h = tf.tanh(tf.matmul(W, x) + b)
#     y = tf.tanh(tf.matmul(W2,h) +b2)
    
    
#     return y, h


pprint(sess.run(y1))
pprint(b)
pprint(three)
print()
pprint(motor_controls)


sesh = tf.Session()
y,h = sesh.run(rnn_cell(x,W,b,W2,b2),feed_dict={x:[[1],[1]]})

In [ ]:
for epoch_indx in range(num_epochs):
    x = 1  # observation from gym
    

In [ ]:
np.cos(theta),np.sin(theta),thetadot

In [43]:
import numpy as np
_num = 5
_cos = np.cos(_num)
_arccos = np.arccos(_cos)
print(_cos,_arccos)

0.283662185463 1.28318530718


In [46]:
print(np.clip(1,0,2))

1


In [1]:
import sys
sys.modules[__name__].__dict__.clear()

import tensorflow as tf
import numpy as np
from pprint import pprint
sesh = tf.Session()

In [2]:
a = tf.constant([1,2,3,4,5,6],shape=[2,3])
b = tf.constant([2,2,2],shape=[3,1])
c = tf.matmul(a,b)

print(sesh.run(c))


[[12]
 [30]]


In [3]:
nodes = 2
_input = np.array([3,3]) # The input at every timestep
#_input = np.random.rand(2,1)
pprint(_input.shape)

x = tf.placeholder(tf.float32,shape=[None,2])

W = tf.get_variable('Multiplication',dtype=tf.float32,initializer=np.array([[1,1],[1,1]],dtype=np.float32))  # The weights to be set by a GA
pprint(sesh.run(W.initializer))

(2,)
None


In [4]:
b = tf.Variable(np.ones((1,nodes)),dtype=tf.float32)  #
# pprint(sesh.run(b.initializer))

In [5]:
mul = tf.multiply(W,x)
# # add = a+b
pprint(sesh.run(mul,feed_dict={x:_input}))

ValueError: Cannot feed value of shape (2,) for Tensor 'Placeholder:0', which has shape '(?, 2)'

In [112]:
import tensorflow as tf
import numpy as np
from pprint import pprint

# a = tf.placeholder(tf.float32,shape=[3,1])

# b = tf.get_variable('bb',dtype=tf.float32,initializer=np.array([[5,6],[7,1]],dtype=np.float32))
# c = tf.get_variable('cc',dtype=tf.float32,initializer=np.array([[2],[2]],dtype=np.float32))

# d = tf.matmul(b,a)






# Number of input states
num_inputs = 1 # one for each input: sin(th), cos(th), torque
num_outputs = 1
# Number of nodes in1st layer of RNN
num_nodes = 2
# Time steps
dt = 0.1 

# The input to the RNN
_sensory_input = tf.placeholder(tf.float32, [1, num_inputs])
zeros = tf.zeros([1, num_nodes-num_inputs],dtype=tf.float32)
sensory_input = tf.concat([_sensory_input,zeros],0) # The input to the RNN cell

init_state = tf.zeros([num_nodes,1],dtype=tf.float32)
prev_state = init_state

num_epochs = 1000  # the max timesteps in open ai gym

# Input weights
ones = tf.ones([1, num_inputs],dtype=tf.float32)
W = tf.concat([ones,zeros],0)
b = tf.zeros([num_nodes,1],dtype=tf.float32)

# Hidden layer weights
set_wieghts = np.random.rand(num_nodes,num_nodes)
set_bias = tf.zeros([num_nodes,1],dtype=tf.float32)
W2 = tf.Variable(set_wieghts,dtype=tf.float32)
b2 = tf.Variable(set_bias,dtype=tf.float32)

# Output layer weights
ones2 = tf.ones([1, num_outputs],dtype=tf.float32)
zeros2 = tf.zeros([1, num_nodes-num_outputs],dtype=tf.float32)
W3 = tf.concat([zeros2,ones2],0)
b3 = tf.zeros([num_nodes,1],dtype=tf.float32)

# Previous state + dt (-Previous State + tanh(W*Previous State+b + Input))
# for epoch in num_epochs:
current_input = tf.tanh(tf.multiply(sensory_input,W) + b)  # may not need to 'tanh'
hidden_weights = tf.tanh(tf.matmul(W2,prev_state) + b2)
current_state = dt* (current_input - prev_state + hidden_weights) + prev_state

out_nodes = tf.multiply(current_state,W3) + b3)
prev_state = current_state



with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess = tf.Session()
    sess.run(init)
    out_list = list()
    out,si,ci,hw,cs =(0,0,0,0,0)
    for epoch_idx in range(100):
        print('si',si)
        print('ci',ci)
        print('hw',hw)
        print('cs',cs)
        print('out',out)
        
        print()
        print()
        print("New data, epoch", epoch_idx)
        if epoch_idx == 0:
#             pprint(sensory_input)
#             pprint(current_input)
#             pprint(hidden_weights)
#             pprint(current_state)
#             pprint(out_nodes)
            out,si,ci,hw,cs = sess.run([out_nodes,sensory_input,current_input,hidden_weights,current_state],feed_dict={_sensory_input:np.array([[1]])})
            prev_state = cs

            out = [out]
        else:
#             pprint(sensory_input)
#             pprint(current_input)
#             pprint(hidden_weights)
#             pprint(current_state)
#             pprint(out_nodes)
            out,si,ci,hw,cs = sess.run([out_nodes,sensory_input,current_input,hidden_weights,current_state],feed_dict={_sensory_input:out_list[epoch_idx-1]})
            prev_state = cs
            out = [out]
        print('what')
        print(prev_state)
        print('si',si)
        print('ci',ci)
        print('hw',hw)
        print('cs',cs)
        print('out',out)
        out_list.append(out[0][:1])
        
# init = tf.global_variables_initializer()
# sesh = tf.Session()
# sesh.run(init)
# print(sesh.run(init_state,feed_dict={sensory_input:[[1]]}))

si 0
ci 0
hw 0
cs 0
out 0


New data, epoch 0
what
[[ 0.07615942]
 [ 0.        ]]
si [[ 1.]
 [ 0.]]
ci [[ 0.76159418]
 [ 0.        ]]
hw [[ 0.]
 [ 0.]]
cs [[ 0.07615942]
 [ 0.        ]]
out [array([[ 0.],
       [ 0.]], dtype=float32)]
si [[ 1.]
 [ 0.]]
ci [[ 0.76159418]
 [ 0.        ]]
hw [[ 0.]
 [ 0.]]
cs [[ 0.07615942]
 [ 0.        ]]
out [array([[ 0.],
       [ 0.]], dtype=float32)]


New data, epoch 1
what
[[ 0.]
 [ 0.]]
si [[ 0.]
 [ 0.]]
ci [[ 0.]
 [ 0.]]
hw [[ 0.]
 [ 0.]]
cs [[ 0.]
 [ 0.]]
out [array([[ 0.],
       [ 0.]], dtype=float32)]
si [[ 0.]
 [ 0.]]
ci [[ 0.]
 [ 0.]]
hw [[ 0.]
 [ 0.]]
cs [[ 0.]
 [ 0.]]
out [array([[ 0.],
       [ 0.]], dtype=float32)]


New data, epoch 2
what
[[ 0.]
 [ 0.]]
si [[ 0.]
 [ 0.]]
ci [[ 0.]
 [ 0.]]
hw [[ 0.]
 [ 0.]]
cs [[ 0.]
 [ 0.]]
out [array([[ 0.],
       [ 0.]], dtype=float32)]
si [[ 0.]
 [ 0.]]
ci [[ 0.]
 [ 0.]]
hw [[ 0.]
 [ 0.]]
cs [[ 0.]
 [ 0.]]
out [array([[ 0.],
       [ 0.]], dtype=float32)]


New data, epoch 3
what
[[ 0.]
 [ 0.]]
si

In [91]:
print(sess.run(current_input,feed_dict={_sensory_input:np.array([[1]])}))

[[ 0.76159418]
 [ 0.        ]]


In [80]:
x = [1,2,3]
print(x[:2])

[1, 2]


In [21]:
# print(sesh.run([d],feed_dict={a:np.array([[2],[3]])}))


np.arccos(-1)/(2*np.pi)*360

np.zeros([num_nodes,1])

array([[ 0.],
       [ 0.]])

In [23]:
import tensorflow as tf
from tensorflow.contrib.rnn import BasicRNNCell

sesh=tf.Session()
print(sesh.run(cell))

In [ ]:
rom __future__ import print_function, division
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

num_epochs = 100
total_series_length = 50000
truncated_backprop_length = 15
state_size = 4
num_classes = 2
echo_step = 3
batch_size = 5
num_batches = total_series_length//batch_size//truncated_backprop_length

def generateData(num_inputs):
#     x = np.array(np.random.choice(2, total_series_length, p=[0.5, 0.5]))
#     y = np.roll(x, echo_step)
#     y[0:echo_step] = 0

#     x = x.reshape((batch_size, -1))  # The first index changing slowest, subseries as rows
#     y = y.reshape((batch_size, -1))
    x = np.random.rand(num_inputs)
    return x # (x, y)

# Number of input states
num_inputs = 1 # one for each input: sin(th), cos(th), torque

# Number of nodes in1st layer of RNN
num_nodes = 2

# The initial state of the RNN
sensory_input = tf.placeholder(tf.float32, [1, num_inputs])
init_state = tf.concat(sensory_input,tf.zeros([1, num_inputs],dtype=tf.float32),0)


# Input weights
W = tf.Variable(np.random.rand(state_size+1, state_size), dtype=tf.float32)
b = tf.Variable(np.zeros((1,state_size)), dtype=tf.float32)

W2 = tf.Variable(np.random.rand(state_size, num_classes),dtype=tf.float32)
b2 = tf.Variable(np.zeros((1,num_classes)), dtype=tf.float32)

# Unpack columns
inputs_series = tf.unpack(batchX_placeholder, axis=1)
labels_series = tf.unpack(batchY_placeholder, axis=1)

# Forward pass
current_state = init_state
states_series = []
for current_input in inputs_series:
    current_input = tf.reshape(current_input, [batch_size, 1])
    input_and_state_concatenated = tf.concat(1, [current_input, current_state])  # Increasing number of columns

    next_state = tf.tanh(tf.matmul(input_and_state_concatenated, W) + b)  # Broadcasted addition
    states_series.append(next_state)
    current_state = next_state

logits_series = [tf.matmul(state, W2) + b2 for state in states_series] #Broadcasted addition
predictions_series = [tf.nn.softmax(logits) for logits in logits_series]

losses = [tf.nn.sparse_softmax_cross_entropy_with_logits(logits, labels) for logits, labels in zip(logits_series,labels_series)]
total_loss = tf.reduce_mean(losses)

train_step = tf.train.AdagradOptimizer(0.3).minimize(total_loss)

def plot(loss_list, predictions_series, batchX, batchY):
    plt.subplot(2, 3, 1)
    plt.cla()
    plt.plot(loss_list)

    for batch_series_idx in range(5):
        one_hot_output_series = np.array(predictions_series)[:, batch_series_idx, :]
        single_output_series = np.array([(1 if out[0] < 0.5 else 0) for out in one_hot_output_series])

        plt.subplot(2, 3, batch_series_idx + 2)
        plt.cla()
        plt.axis([0, truncated_backprop_length, 0, 2])
        left_offset = range(truncated_backprop_length)
        plt.bar(left_offset, batchX[batch_series_idx, :], width=1, color="blue")
        plt.bar(left_offset, batchY[batch_series_idx, :] * 0.5, width=1, color="red")
        plt.bar(left_offset, single_output_series * 0.3, width=1, color="green")

    plt.draw()
    plt.pause(0.0001)


with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    plt.ion()
    plt.figure()
    plt.show()
    loss_list = []

    for epoch_idx in range(num_epochs):
        x,y = generateData()
        _current_state = np.zeros((batch_size, state_size))

        print("New data, epoch", epoch_idx)

        for batch_idx in range(num_batches):
            start_idx = batch_idx * truncated_backprop_length
            end_idx = start_idx + truncated_backprop_length

            batchX = x[:,start_idx:end_idx]
            batchY = y[:,start_idx:end_idx]

            _total_loss, _train_step, _current_state, _predictions_series = sess.run(
                [total_loss, train_step, current_state, predictions_series],
                feed_dict={
                    batchX_placeholder:batchX,
                    batchY_placeholder:batchY,
                    init_state:_current_state
                })

            loss_list.append(_total_loss)

            if batch_idx%100 == 0:
                print("Step",batch_idx, "Loss", _total_loss)
                plot(loss_list, _predictions_series, batchX, batchY)

plt.ioff()
plt.show()
view raw