In [1]:
import tensorflow as tf
from __future__ import absolute_import, print_function, division
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = tf.placeholder(tf.float32,shape=[None,2])

W = tf.get_variable('Multiplication',dtype=tf.float32,initializer=np.array([[1,1],[1,1]],dtype=np.float32))  # The weights to be set by a GA

with tf.name_scope("Wx_b") as scope:
    #
    model = tf.matmul(x,W)

data = np.array([[3,3],[3,4],[3,3]])


In [3]:

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    res = sess.run(model, feed_dict={x: data})
print(res)

[[ 6.  6.]
 [ 7.  7.]
 [ 6.  6.]]


In [32]:
print(np.random.rand(2,1))

def make_rnn_cell(x,weights=None,biases=None,name=None):
    
    

def



[[ 0.98528239]
 [ 0.91075923]]


In [20]:
dt = 0.01;
T = 10000;

time = np.linspace(0,T,(T+dt)/dt)

N = 2  # Number of nodes

W = np.array([[0.1,1.1],[1.1,0.1]])
y = tf.Variable(tf.zeros((N,len(time))))

theta = np.random.rand(N,1)*0.0 # Theta is just a parameter
Iconf = floor(rand(N,1)+0.5); # What is Iconf?
window_size = 5;
pulse_time =6;

pulse_dur=1;
Imag=0.0;
I=0;

for i=2:length(time)
    y(:,i) = y(:,i-1) +dt*(-y(:,i-1)+tanh( W*y(:,i-1) +theta+I));
    if(mod(i,floor(pulse_time/dt))<pulse_dur/dt)
        I=Imag*Iconf;
    else
        I=0;
    end





# Construct a `Session` to execute the graph.
sess = tf.Session()

# Execute the graph and store the value that `e` represents in `result`.
result = sess.run(e)

/Users/dattlee/miniconda/envs/pendulum_v0_py3/lib/python3.6/site-packages/ipykernel/__main__.py:4: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.


In [ ]:

def main(_):
  # Import data
  # mnist = input_data.read_data_sets(FLAGS.data_dir, one_hot=True)

  # Create the model
  x = tf.placeholder(tf.float32, [None, 784])
  W = tf.Variable(tf.zeros([784, 10]))
  b = tf.Variable(tf.zeros([10]))
  y = tf.matmul(x, W) + b

  # Define loss and optimizer
  y_ = tf.placeholder(tf.float32, [None, 10])

  # The raw formulation of cross-entropy,
  #
  #   tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(tf.nn.softmax(y)),
  #                                 reduction_indices=[1]))
  #
  # can be numerically unstable.
  #
  # So here we use tf.nn.softmax_cross_entropy_with_logits on the raw
  # outputs of 'y', and then average across the batch.
  cross_entropy = tf.reduce_mean(
      tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=y))
  train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

  sess = tf.InteractiveSession()
  tf.global_variables_initializer().run()
  # Train
  for _ in range(1000):
    batch_xs, batch_ys = mnist.train.next_batch(100)
    sess.run(train_step, feed_dict={x: batch_xs, y_: batch_ys})

  # Test trained model
  correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))
  accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
  print(sess.run(accuracy, feed_dict={x: mnist.test.images,
                                      y_: mnist.test.labels}))


In [24]:
# Build a dataflow graph.
c = tf.constant([[1.0, 2.0], [3.0, 4.0]])
d = tf.constant([[1.0, 1.0], [0.0, 1.0]])
e = tf.matmul(c, d)

# Construct a `Session` to execute the graph.
sess = tf.Session()

# Execute the graph and store the value that `e` represents in `result`.
result = sess.run(e)

In [25]:
print(result)

[[ 1.  3.]
 [ 3.  7.]]


In [26]:
print(tf.global_variables())

[]
